/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Rent_Rover;

import Rent_Rover.DataBases.DB;
import java.awt.Cursor;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author PC MOD NEPAL
 */


public class Form_Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Login.class.getName());

    /**
     * Creates new form Form_Login
     */
    public Form_Login() {
        initComponents();
        
        this.setLocationRelativeTo(null);//center the form
        //display images on the jLabels
      // brandLogo.setIcon(new javax.swing.ImageIcon (getClass().getResource("images/logo.jpg")));
       
    }

    /**^
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        jPanel4 = new Rent_Rover.CoolPanel(30);
        topic = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        showpassword = new javax.swing.JCheckBox();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gotoSignup = new javax.swing.JLabel();
        forgotPass = new javax.swing.JLabel();
        welcomeTo1 = new javax.swing.JLabel();
        RentRover = new javax.swing.JLabel();
        Cross = new javax.swing.JButton();
        RRR = new javax.swing.JLabel();
        brandLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        Close.setFont(new java.awt.Font("Verdana", 0, 48)); // NOI18N
        Close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Close.setText("X");
        jPanel3.add(Close);
        Close.setBounds(1850, 30, 50, 50);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0,100));

        topic.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        topic.setForeground(new java.awt.Color(255, 255, 255));
        topic.setText("Login Account");

        UsernameField.setForeground(new java.awt.Color(102, 102, 102));
        UsernameField.setText("example123");
        UsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusLost(evt);
            }
        });
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        PasswordField.setForeground(new java.awt.Color(102, 102, 102));
        PasswordField.setText("password");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(0, 153, 255));
        LoginButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginButtonMouseEntered(evt);
            }
        });
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        showpassword.setBackground(new java.awt.Color(255, 255, 255));
        showpassword.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        showpassword.setForeground(new java.awt.Color(255, 255, 255));
        showpassword.setText("Show Password");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });

        Username.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(255, 255, 255));
        Username.setText("Username");

        Password.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password");

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        gotoSignup.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        gotoSignup.setForeground(new java.awt.Color(0, 153, 204));
        gotoSignup.setText("SignUp?");
        gotoSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoSignupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gotoSignupMouseEntered(evt);
            }
        });

        forgotPass.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        forgotPass.setForeground(new java.awt.Color(0, 153, 204));
        forgotPass.setText("Forgot Password");
        forgotPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UsernameField)
                            .addComponent(PasswordField)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(forgotPass, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gotoSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(showpassword)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Username)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(topic, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(topic)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(showpassword)
                .addGap(56, 56, 56)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gotoSignup)
                    .addComponent(forgotPass))
                .addContainerGap())
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(820, 90, 450, 500);

        welcomeTo1.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        welcomeTo1.setForeground(new java.awt.Color(255, 255, 255));
        welcomeTo1.setText("Welcome to");
        jPanel3.add(welcomeTo1);
        welcomeTo1.setBounds(120, 170, 240, 60);

        RentRover.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        RentRover.setForeground(new java.awt.Color(0, 153, 204));
        RentRover.setText("RentRover");
        jPanel3.add(RentRover);
        RentRover.setBounds(370, 170, 200, 60);

        Cross.setBackground(new java.awt.Color(0, 0, 0,100));
        Cross.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        Cross.setForeground(new java.awt.Color(255, 0, 0));
        Cross.setText("X");
        Cross.setBorder(null);
        Cross.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrossMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CrossMouseEntered(evt);
            }
        });
        Cross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrossActionPerformed(evt);
            }
        });
        jPanel3.add(Cross);
        Cross.setBounds(1310, 10, 30, 30);

        RRR.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        RRR.setForeground(new java.awt.Color(255, 255, 255));
        RRR.setText("Rent, Ride, Repeat!");
        jPanel3.add(RRR);
        RRR.setBounds(140, 240, 160, 40);

        brandLogo.setBackground(new java.awt.Color(92, 165, 238));
        brandLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProjectImages/logo.jpg"))); // NOI18N
        brandLogo.setOpaque(true);
        brandLogo.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.add(brandLogo);
        brandLogo.setBounds(0, 0, 1366, 690);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if(showpassword.isSelected())
        {
            PasswordField.setEchoChar((char)0);
        }
        else
        {
            PasswordField.setEchoChar('*');
        }
    }//GEN-LAST:event_showpasswordActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
                                          
    String username = UsernameField.getText().trim();
    String password = String.valueOf(PasswordField.getPassword()).trim();

    PreparedStatement ps;
    ResultSet rs;

    // ===== Admin Login =====
    String adminQuery = "SELECT * FROM `users` WHERE `username`=? AND password=?";
    try {
        ps = DB.getConnection().prepareStatement(adminQuery);
        ps.setString(1, username);
        ps.setString(2, password);
        rs = ps.executeQuery();

        if(rs.next()) { // Admin detected
            System.out.println("Admin Login");

            // Ask for admin code
            String storedCode = rs.getString("code"); // fetch from DB
            String inputCode = JOptionPane.showInputDialog(this, "Enter your admin code:", "Admin Verification", JOptionPane.PLAIN_MESSAGE);

            if(inputCode != null && inputCode.equals(storedCode)) {
                CustomPopup.showInfo(this, "Login Successful!", "Success");
                new Admin_Dash().setVisible(true);
                this.dispose();
            } else {
                CustomPopup.showError(this, "Incorrect admin code! Access denied.", "Error");
            }

        } else {
            // ===== Customer Login =====
            // ===== Customer Login =====
String customerQuery = "SELECT * FROM `customer` WHERE `username`=?";
try {
    ps = DB.getConnection().prepareStatement(customerQuery);
    ps.setString(1, username);
    rs = ps.executeQuery();

    if(rs.next()) {
        String storedHash = rs.getString("password"); // hashed password from DB

        if(BCrypt.checkpw(password, storedHash)) {
            // Password matches
            System.out.println("Customer Login");

            // Get profile picture as byte array
            byte[] profilePic = rs.getBytes("profile_picture");

            // Check if user already exists in logged_in_user
            String checkLoggedIn = "SELECT * FROM `logged_in_user` WHERE username=?";
            PreparedStatement psCheck = DB.getConnection().prepareStatement(checkLoggedIn);
            psCheck.setString(1, username);
            ResultSet rsCheck = psCheck.executeQuery();

            if(!rsCheck.next()) {
                // Insert into logged_in_user
                String insertLoggedIn = "INSERT INTO logged_in_user (username, profile_picture) VALUES (?, ?)";
                PreparedStatement psInsert = DB.getConnection().prepareStatement(insertLoggedIn);
                psInsert.setString(1, username);
                psInsert.setBytes(2, profilePic);
                psInsert.executeUpdate();
            }

            // Proceed to customer dashboard
            JOptionPane.showMessageDialog(this, "Customer Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
            String enteredUsername = UsernameField.getText().trim(); // username from login
new Primary_Screen_Logged(enteredUsername).setVisible(true);
this.dispose();


        } else {
            // Wrong password
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Error", JOptionPane.INFORMATION_MESSAGE);
            new Form_Login().setVisible(true);
            this.dispose();
        }
    } else {
        // Username not found
        JOptionPane.showMessageDialog(this, "Invalid Username or Password!", "Error", JOptionPane.INFORMATION_MESSAGE);
        new Form_Login().setVisible(true);
        this.dispose();
    }

} catch(SQLException ex) {
    System.out.println("Customer DB Error: " + ex.getMessage());
    JOptionPane.showMessageDialog(this, "Customer DB Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

        }

    } catch(SQLException ex) {
        System.out.println("Admin DB Error: " + ex.getMessage());
        JOptionPane.showMessageDialog(this, "Admin DB Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }







    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void LoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseEntered
        LoginButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));// TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseEntered

    private void CrossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrossActionPerformed

    private void CrossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseClicked
    this.dispose();    // TODO add your handling code here:
    
    }//GEN-LAST:event_CrossMouseClicked

    private void UsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusGained
        //clears text if username ko field is Example123
        if (UsernameField.getText().trim().toLowerCase().equals("example123"))
        {
            UsernameField.setText("");
        }
        
    }//GEN-LAST:event_UsernameFieldFocusGained

    private void UsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusLost
        if((UsernameField.getText().trim().toLowerCase().equals("example123"))||UsernameField.getText().trim().toLowerCase().equals(""))
        {
                    {
                        UsernameField.setText("example123");
                    }
        }
    }//GEN-LAST:event_UsernameFieldFocusLost

    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        String password=String.valueOf(PasswordField.getPassword());
        if(password.trim().toLowerCase().equals("password"))
        {
            PasswordField.setText("");
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        String password= String.valueOf(PasswordField.getPassword());
        if((password.trim().toLowerCase().equals("example123"))||(password.trim().toLowerCase().equals("")))
        {
            password.trim().toLowerCase().equals("");
                    {
                        PasswordField.setText("example123");
                    }
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    private void CrossMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrossMouseEntered
    Cross.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));        // TODO add your handling code here:
    }//GEN-LAST:event_CrossMouseEntered

    private void gotoSignupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoSignupMouseEntered
        gotoSignup.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_gotoSignupMouseEntered

    private void gotoSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoSignupMouseClicked
        new Form_SignUp().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gotoSignupMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Close;
    private javax.swing.JButton Cross;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RRR;
    private javax.swing.JLabel RentRover;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel brandLogo;
    private javax.swing.JLabel forgotPass;
    private javax.swing.JLabel gotoSignup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox showpassword;
    private javax.swing.JLabel topic;
    private javax.swing.JLabel welcomeTo1;
    // End of variables declaration//GEN-END:variables


}
