/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Rent_Rover;

/**
 *
 * @author PC MOD NEPAL
 */
import Rent_Rover.DataBases.DB;
import java.awt.Color;
import Rent_Rover.GradientPanel;
import Rent_Rover.GradientPanel.Direction;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Primary_Screen_Logged extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Primary_Screen_Logged.class.getName());
    private javax.swing.JPopupMenu suggestionPopup = new javax.swing.JPopupMenu();

    /**
     * Creates new form Primary_Screen
     */
    
    private String username; // store the logged-in user's username

public Primary_Screen_Logged(String loggedInUsername) {
    this.username = loggedInUsername; // store for later use
    initComponents();
    
    ImageScaler.setScaledImage(RR_logo, "C:\\Users\\97798\\Desktop\\ProjectImages\\RR logo.png");
    ImageScaler.setScaledImage(CarLogo, "C:\\Users\\97798\\Desktop\\ProjectImages\\lincoln navigator.png");
    ImageScaler.setScaledImage(Calendar,"C:\\Users\\97798\\Desktop\\ProjectImages\\calendar.png" );
    ImageScaler.setScaledImage(calendar2,"C:\\Users\\97798\\Desktop\\ProjectImages\\calendar.png" );
    ImageScaler.setScaledImage(pickuplogo,"C:\\Users\\97798\\Desktop\\ProjectImages\\location.png" );
    ImageScaler.setScaledImage(DropOfflogo,"C:\\Users\\97798\\Desktop\\ProjectImages\\location.png" );
    pickuplocation.addItem("Select PickUp Location");
    dropofflocation.addItem("Select DropOff Location");
    
    loadLocations();
    setProfilePictureFromCustomer(); // fetch picture directly from customer table
}
public void setProfilePictureFromCustomer() {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        conn = DB.getConnection(); // your DB connection method
        String query = "SELECT profile_picture FROM customer WHERE username = ?";
        ps = conn.prepareStatement(query);
        ps.setString(1, username);
        rs = ps.executeQuery();

        if (rs.next()) {
            byte[] imgBytes = rs.getBytes("profile_picture"); // assuming longblob in customer table
            if (imgBytes != null) {
                ImageIcon icon = new ImageIcon(imgBytes);
                Image img = icon.getImage().getScaledInstance(pfp.getWidth(), pfp.getHeight(), Image.SCALE_SMOOTH);
                pfp.setIcon(new ImageIcon(img));
                CircularLabel.makeCircular(pfp);
            } else {
                pfp.setIcon(null); // optional default image
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    } finally {
        try { if (rs != null) rs.close(); } catch (SQLException e) { }
        try { if (ps != null) ps.close(); } catch (SQLException e) { }
        try { if (conn != null) conn.close(); } catch (SQLException e) { }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottom = new ImageScalerP("C:\\Users\\97798\\Desktop\\ProjectImages\\dune.jpg");
        jLabel4 = new javax.swing.JLabel();
        CarLogo = new javax.swing.JLabel();
        whitepanel = new ImageScalerP("C:\\Users\\97798\\Desktop\\ProjectImages\\whitebg.jpg");
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RR_logo = new javax.swing.JLabel();
        homee = new javax.swing.JLabel();
        pfp = new javax.swing.JLabel();
        renter = new javax.swing.JLabel();
        your_bookings = new javax.swing.JLabel();
        your_rentals = new javax.swing.JLabel();
        book = new javax.swing.JPanel();
        pickup = new RoundedPanel(25);
        dateField1 = new RoundedTextField(25);
        Calendar = new javax.swing.JLabel();
        dropoff = new RoundedPanel(25);
        calendar2 = new javax.swing.JLabel();
        dateField2 = new RoundedTextField(25);
        BOOKnow = new Rent_Rover.CoolButton("BOOK NOW");
        jPanel1 = new javax.swing.JPanel();
        pickuplogo = new javax.swing.JLabel();
        pickuplocation = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        DropOfflogo = new javax.swing.JLabel();
        dropofflocation = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bottom.setBackground(new java.awt.Color(102, 255, 255));

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel4.setText("Rover on Demand");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        CarLogo.setBackground(new java.awt.Color(0, 0, 255));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Rent, Ride, Repeat");

        jLabel1.setFont(new java.awt.Font("Perpetua", 3, 36)); // NOI18N
        jLabel1.setText("RentRover");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        RR_logo.setMaximumSize(new java.awt.Dimension(76, 51));

        homee.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        homee.setText("Home");
        homee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeeMouseClicked(evt);
            }
        });

        renter.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        renter.setText("Become a Renter");
        renter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        renter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                renterMouseClicked(evt);
            }
        });

        your_bookings.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        your_bookings.setText("Your Bookings");
        your_bookings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        your_bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                your_bookingsMouseClicked(evt);
            }
        });

        your_rentals.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        your_rentals.setText("Your Rentals");
        your_rentals.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        your_rentals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                your_rentalsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout whitepanelLayout = new javax.swing.GroupLayout(whitepanel);
        whitepanel.setLayout(whitepanelLayout);
        whitepanelLayout.setHorizontalGroup(
            whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitepanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(RR_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(whitepanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(homee)
                .addGap(116, 116, 116)
                .addComponent(your_bookings, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(your_rentals)
                .addGap(110, 110, 110)
                .addComponent(renter)
                .addGap(86, 86, 86)
                .addComponent(pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        whitepanelLayout.setVerticalGroup(
            whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitepanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homee)
                    .addComponent(renter)
                    .addComponent(your_bookings, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(your_rentals, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(whitepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(whitepanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RR_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        book.setOpaque(false);

        dateField1.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        dateField1.setText("Select PickUp Date");
        dateField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateField1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pickupLayout = new javax.swing.GroupLayout(pickup);
        pickup.setLayout(pickupLayout);
        pickupLayout.setHorizontalGroup(
            pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pickupLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        pickupLayout.setVerticalGroup(
            pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pickupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pickupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dateField2.setFont(new java.awt.Font("Perpetua", 0, 14)); // NOI18N
        dateField2.setText("Select Return Date");
        dateField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateField2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dropoffLayout = new javax.swing.GroupLayout(dropoff);
        dropoff.setLayout(dropoffLayout);
        dropoffLayout.setHorizontalGroup(
            dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropoffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField2, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        dropoffLayout.setVerticalGroup(
            dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropoffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dropoffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateField2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        BOOKnow.setText("Search Now");
        BOOKnow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOOKnowActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pickuplogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pickuplocation, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pickuplocation)
                    .addComponent(pickuplogo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setOpaque(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DropOfflogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropofflocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropofflocation)
                    .addComponent(DropOfflogo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout bookLayout = new javax.swing.GroupLayout(book);
        book.setLayout(bookLayout);
        bookLayout.setHorizontalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BOOKnow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bookLayout.createSequentialGroup()
                        .addComponent(pickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dropoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(bookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bookLayout.setVerticalGroup(
            bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(bookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pickup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(BOOKnow, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whitepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(324, 324, 324)
                        .addComponent(CarLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(whitepanel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CarLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
       new Primary_Screen_Logged(this.username).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void dateField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateField1MouseClicked
         // Create a calendar dialog
    com.toedter.calendar.JCalendar calendar = new com.toedter.calendar.JCalendar();
    
    // Create a dialog to hold the calendar
    JDialog dialog = new JDialog();
    dialog.setModal(true);
    dialog.setTitle("Select Date");
    dialog.getContentPane().add(calendar);
    dialog.pack();
    dialog.setLocationRelativeTo(dateField1);

    // Add a listener to detect date selection
    calendar.addPropertyChangeListener("calendar", evt2 -> {
        java.util.Calendar selected = calendar.getCalendar();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        dateField1.setText(sdf.format(selected.getTime()));
        dialog.dispose(); // close the dialog after selection
    });

    dialog.setVisible(true);
    }//GEN-LAST:event_dateField1MouseClicked

    private void dateField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateField2MouseClicked
         com.toedter.calendar.JCalendar calendar = new com.toedter.calendar.JCalendar();
    
    // Create a dialog to hold the calendar
    JDialog dialog = new JDialog();
    dialog.setModal(true);
    dialog.setTitle("Select Date");
    dialog.getContentPane().add(calendar);
    dialog.pack();
    dialog.setLocationRelativeTo(dateField2);

    // Add a listener to detect date selection
    calendar.addPropertyChangeListener("calendar", evt2 -> {
        java.util.Calendar selected = calendar.getCalendar();
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        dateField2.setText(sdf.format(selected.getTime()));
        dialog.dispose(); // close the dialog after selection
    });

    dialog.setVisible(true);
    }//GEN-LAST:event_dateField2MouseClicked
    private void loadLocations() {
    try (Connection conn = DB.getConnection();
         PreparedStatement ps = conn.prepareStatement("SELECT DISTINCT location FROM bookings");
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            String loc = rs.getString("location");
            pickuplocation.addItem(loc);
            dropofflocation.addItem(loc);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        StylishPopup.showError(this, "Failed to load locations: " + e.getMessage());
    }
}

    private void BOOKnowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOOKnowActionPerformed
                                               
    try {
        // Get values from fields
        String pickup = (String) pickuplocation.getSelectedItem();
        String dropoff = (String) dropofflocation.getSelectedItem();

// Validation
if (pickup.equals("Select PickUp Location") || dropoff.equals("Select DropOff Location")) {
    StylishPopup.showError(this, "Please select both pickup and dropoff locations!");
    return;
}

        String pickupDate = dateField1.getText().trim(); 
        String dropoffDate = dateField2.getText().trim();

        // Validate fields
        if (pickup.isEmpty() || pickup.equalsIgnoreCase("PickUp Location") ||
            dropoff.isEmpty() || dropoff.equalsIgnoreCase("DropOff Location") ||
            pickupDate.isEmpty() || dropoffDate.isEmpty()) {

            StylishPopup.showError(this, "Please fill all fields!");
            return;
        }

        // Validate max length
        if (pickup.length() > 100 || dropoff.length() > 100) {
            StylishPopup.showError(this, "Location cannot exceed 100 characters!");
            return;
        }

        // Validate dates
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.util.Date pickDateObj = sdf.parse(pickupDate);
        java.util.Date dropDateObj = sdf.parse(dropoffDate);

        if (!dropDateObj.after(pickDateObj) && !dropDateObj.equals(pickDateObj)) {
            StylishPopup.showError(this, "Drop-off date must be same or after pick-up date!");
            return;
        }

        // ✅ Pass booking details AND username to dashboard
        Customer_DashBoard_Logged dashboard = new Customer_DashBoard_Logged(
            pickup, dropoff, pickupDate, dropoffDate, this.username
        );
        this.dispose();
        dashboard.setVisible(true);
        

    } catch (Exception ex) {
        ex.printStackTrace();
        StylishPopup.showError(this, "Error: " + ex.getMessage());
    }


     
     
    }//GEN-LAST:event_BOOKnowActionPerformed

    private void homeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeeMouseClicked
        this.dispose();
       new Primary_Screen_Logged(this.username).setVisible(true);
    }//GEN-LAST:event_homeeMouseClicked

    private void renterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_renterMouseClicked
        try {
        

        // ✅ Pass booking details AND username to dashboard
        RenterDashBoard renter = new RenterDashBoard(
            this.username
        );
        this.dispose();
        renter.setVisible(true);
        

    } catch (Exception ex) {
        ex.printStackTrace();
        StylishPopup.showError(this, "Error: " + ex.getMessage());
    }
    }//GEN-LAST:event_renterMouseClicked

    private void your_bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_your_bookingsMouseClicked
        your_bookings rentals = new your_bookings(this.username);
    rentals.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_your_bookingsMouseClicked

    private void your_rentalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_your_rentalsMouseClicked
        Own_Rentals rentals = new Own_Rentals(this.username);
    rentals.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_your_rentalsMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new Primary_Screen_Logged("testuser").setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOOKnow;
    private javax.swing.JLabel Calendar;
    private javax.swing.JLabel CarLogo;
    private javax.swing.JLabel DropOfflogo;
    private javax.swing.JLabel RR_logo;
    private javax.swing.JPanel book;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel calendar2;
    private javax.swing.JTextField dateField1;
    private javax.swing.JTextField dateField2;
    private javax.swing.JPanel dropoff;
    private javax.swing.JComboBox<String> dropofflocation;
    private javax.swing.JLabel homee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel pfp;
    private javax.swing.JPanel pickup;
    private javax.swing.JComboBox<String> pickuplocation;
    private javax.swing.JLabel pickuplogo;
    private javax.swing.JLabel renter;
    private javax.swing.JPanel whitepanel;
    private javax.swing.JLabel your_bookings;
    private javax.swing.JLabel your_rentals;
    // End of variables declaration//GEN-END:variables
}
