/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Rent_Rover;

import Rent_Rover.DataBases.DB;
import java.awt.Color;
import Rent_Rover.GradientPanel;
import Rent_Rover.GradientPanel.Direction;
import java.awt.Cursor;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author PC MOD NEPAL
 */


public class RenterDashBoard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RenterDashBoard.class.getName());
    

    /**
     * Creates new form Form_Login
     */
    
public RenterDashBoard() {
    initComponents();
    this.setLocationRelativeTo(null);
}


   private String username;

public RenterDashBoard(String username) {
    initComponents();
    this.username = username; // save it for later use
    setProfilePicture(username); // optional: show profile pic
}


    private void setProfilePicture(String username) {
    
    try {
        Connection con = DB.getConnection();
        String query = "SELECT username, profile_picture FROM customer WHERE username = ?";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, username);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            // Set username in text field
            ufield.setText(rs.getString("username"));

            // Set profile picture in JLabel
            byte[] imgBytes = rs.getBytes("profile_picture");
            if (imgBytes != null) {
                ImageIcon imageIcon = new ImageIcon(imgBytes);
                Image image = imageIcon.getImage().getScaledInstance(pfp.getWidth(), pfp.getHeight(), Image.SCALE_SMOOTH);
                pfp.setIcon(new ImageIcon(image));
                CircularLabel.makeCircular(pfp);
            }
        }

        rs.close();
        ps.close();
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
    
}

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pfp = new javax.swing.JLabel();
        RentButton = new javax.swing.JLabel();
        carpfp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ufield = new RoundedTextField(10);
        uname = new javax.swing.JLabel();
        brand = new javax.swing.JLabel();
        bfield = new RoundedTextField(10);
        model = new javax.swing.JLabel();
        mfield = new RoundedTextField(10);
        location = new javax.swing.JLabel();
        mfield1 = new RoundedTextField(10);
        price = new javax.swing.JLabel();
        pfield = new RoundedTextField(10);
        jLabel6 = new javax.swing.JLabel();
        select_vehicle = new javax.swing.JLabel();
        brandLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.setLayout(null);

        pfp.setBackground(new java.awt.Color(0, 255, 0));
        pfp.setOpaque(true);
        jPanel3.add(pfp);
        pfp.setBounds(1280, 20, 60, 60);

        RentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentButtonMouseClicked(evt);
            }
        });
        jPanel3.add(RentButton);
        RentButton.setBounds(267, 250, 150, 270);

        carpfp.setBackground(new java.awt.Color(0, 255, 0));
        carpfp.setOpaque(true);
        jPanel3.add(carpfp);
        carpfp.setBounds(830, 270, 380, 270);

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setOpaque(false);

        ufield.setEditable(false);
        ufield.setBackground(new java.awt.Color(0, 0, 0));
        ufield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ufield.setForeground(new java.awt.Color(255, 255, 255));
        ufield.setOpaque(true);

        uname.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        uname.setForeground(new java.awt.Color(255, 255, 255));
        uname.setText("Username");

        brand.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        brand.setForeground(new java.awt.Color(255, 255, 255));
        brand.setText("Brand");

        bfield.setBackground(new java.awt.Color(0, 0, 0));
        bfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bfield.setForeground(new java.awt.Color(255, 255, 255));

        model.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        model.setForeground(new java.awt.Color(255, 255, 255));
        model.setText("Model");

        mfield.setBackground(new java.awt.Color(0, 0, 0));
        mfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mfield.setForeground(new java.awt.Color(255, 255, 255));

        location.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        location.setForeground(new java.awt.Color(255, 255, 255));
        location.setText("Location");

        mfield1.setBackground(new java.awt.Color(0, 0, 0));
        mfield1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mfield1.setForeground(new java.awt.Color(255, 255, 255));

        price.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        price.setForeground(new java.awt.Color(255, 255, 255));
        price.setText("Price/Day");

        pfield.setBackground(new java.awt.Color(0, 0, 0));
        pfield.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pfield.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pfield, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(mfield1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                        .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mfield)
                        .addComponent(uname)
                        .addComponent(ufield)
                        .addComponent(brand)
                        .addComponent(bfield)
                        .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(price))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(uname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ufield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(brand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(model)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(location)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(480, 220, 310, 360);

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Become @ Renter");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(690, 170, 280, 50);

        select_vehicle.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        select_vehicle.setForeground(new java.awt.Color(255, 255, 255));
        select_vehicle.setText("Select Your Vehicle");
        select_vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                select_vehicleMouseClicked(evt);
            }
        });
        jPanel3.add(select_vehicle);
        select_vehicle.setBounds(900, 560, 250, 40);

        brandLogo.setBackground(new java.awt.Color(92, 165, 238));
        brandLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC MOD NEPAL\\OneDrive\\Desktop\\ProjectImages\\Untitled (Copy).png")); // NOI18N
        brandLogo.setOpaque(true);
        brandLogo.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel3.add(brandLogo);
        brandLogo.setBounds(0, 0, 1370, 770);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public class ImageUtils {
    public static byte[] imageIconToBytes(ImageIcon icon) throws Exception {
        java.awt.image.BufferedImage bImage = new java.awt.image.BufferedImage(
                icon.getIconWidth(),
                icon.getIconHeight(),
                java.awt.image.BufferedImage.TYPE_INT_ARGB
        );
        java.awt.Graphics2D g2 = bImage.createGraphics();
        icon.paintIcon(null, g2, 0, 0);
        g2.dispose();

        java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
        javax.imageio.ImageIO.write(bImage, "png", baos);
        return baos.toByteArray();
    }
}

    private void RentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentButtonMouseClicked
       try {
        // 1. Get values from fields
        String username = this.username; // already set from login
        String brandText = bfield.getText().trim();
        String modelText = mfield.getText().trim();
        String locationText = mfield1.getText().trim();
        String priceText = pfield.getText().trim();

        // 2. Check if all fields are filled
        if (brandText.isEmpty() || modelText.isEmpty() || locationText.isEmpty() || priceText.isEmpty() || carpfp.getIcon() == null) {
            StylishPopup.showError(this, "Please fill all details and select a vehicle image!");
            return;
        }

        // 3. Convert vehicle image to byte[]
        ImageIcon icon = (ImageIcon) carpfp.getIcon();
        byte[] carImage = ImageUtils.imageIconToBytes(icon); // utility function

        // 4. Insert into bookings table
        Connection con = DB.getConnection();
        String query = "INSERT INTO bookings (username, brand, model, location, price_per_day, vehicle_image) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, username);
        ps.setString(2, brandText);
        ps.setString(3, modelText);
        ps.setString(4, locationText);
        ps.setString(5, priceText);
        ps.setBytes(6, carImage);

        int inserted = ps.executeUpdate();
        if (inserted > 0) {
            StylishPopup.showSuccess(this, "Vehicle successfully registered!");
            new Primary_Screen_Logged(this.username).setVisible(true);
            this.dispose();
            // Optionally clear fields or redirect
        }

        ps.close();
        con.close();

    } catch (Exception e) {
        e.printStackTrace();
        StylishPopup.showError(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_RentButtonMouseClicked

    private void select_vehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_select_vehicleMouseClicked
        select_vehicle.setCursor(new Cursor(Cursor.HAND_CURSOR));
select_vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        int option = fileChooser.showOpenDialog(null);
        if (option == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            String path = file.getAbsolutePath();

            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);
            java.awt.Image img = icon.getImage().getScaledInstance(carpfp.getWidth(), carpfp.getHeight(), java.awt.Image.SCALE_SMOOTH);
            carpfp.setIcon(new javax.swing.ImageIcon(img));
            carpfp.putClientProperty("imgPath", path); // store path for later
        }
    }
});

    }//GEN-LAST:event_select_vehicleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RenterDashBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RentButton;
    private javax.swing.JTextField bfield;
    private javax.swing.JLabel brand;
    private javax.swing.JLabel brandLogo;
    private javax.swing.JLabel carpfp;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel location;
    private javax.swing.JTextField mfield;
    private javax.swing.JTextField mfield1;
    private javax.swing.JLabel model;
    private javax.swing.JTextField pfield;
    private javax.swing.JLabel pfp;
    private javax.swing.JLabel price;
    private javax.swing.JLabel select_vehicle;
    private javax.swing.JTextField ufield;
    private javax.swing.JLabel uname;
    // End of variables declaration//GEN-END:variables


}
